# Generated by Django 4.0.4 on 2022-04-25 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(max_length=64, verbose_name='트랜잭션ID')),
                ('result', models.CharField(choices=[('SUCCESS', '성공'), ('FAILED', '실패')], default='FAILED', help_text='트랜잭션 결과값', max_length=7, verbose_name='결과')),
                ('status', models.BooleanField(choices=[('CONFIRMED', '컨펌됨'), ('UNCONFIRMED', '컨펌대기중')], default='UNCONFIRMED', help_text='컨펌상태에 의한 결과값 ( > 20 일 경우 True', max_length=11, verbose_name='상태')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
