# Generated by Django 4.0.4 on 2022-05-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0006_alter_transaction_result_alter_transaction_tx_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="message",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=256,
                null=True,
                verbose_name="message",
            ),
        ),
    ]
