# Generated by Django 4.0.4 on 2022-04-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='passphrase',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='암호'),
        ),
    ]
