# Generated by Django 4.0.4 on 2022-04-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_created_at_wallet_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='삭제됨'),
        ),
    ]
