# Generated by Django 4.0.4 on 2022-04-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_wallet_passphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='active',
            field=models.BooleanField(default=False, verbose_name='활성상태'),
        ),
    ]
